version: '3'
services:
  nanotifyaccount:
    image: "benjjefferies/nanonotifyaccount"
    environment:
    - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
    - DATABASE_URL=sqlite:////var/test.db
    ports:
    - "5000:5000"
    volumes:
    - ../:/var/
    restart: always
    network_mode: host
    logging:
        driver: json-file
        options:
            max-size: 50m
  nanotify:
    image: "benjjefferies/nanonotifier"
    environment:
    - EMAIL_ENABLED=True
    - FCM_ENABLED=True
    - DATABASE_URL=sqlite:////var/test.db
    - BCRYPT_SECRET=${BCRYPT_SECRET}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - TIMEOUT=5
    - RAIBLOCKS_HOST=[::1]
    - WEBHOOK_ENABLED=True
    - FCM_API_KEY=${FCM_API_KEY}
    volumes:
    - ../:/var/
    network_mode: host
    restart: always
    logging:
        driver: json-file
        options:
            max-size: 50m
  caddy:
    image: "abiosoft/caddy"
    ports:
    - "443:443"
    - "80:80"
    environment:
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    volumes:
    - ./caddy:/etc/
    - $HOME/.caddy:/.caddy
    - /etc/ssl/certs/:/etc/ssl/certs/
    restart: always
    network_mode: host
    logging:
        driver: json-file
        options:
            max-size: 50m
  nano:
    image: "nanocurrency/nano"
    volumes:
    - ./nano:/root
    restart: always
    ports:
    - "7076:7076"
    logging:
        driver: json-file
        options:
            max-size: 50m
