version: '3'
services:
  nanotifyaccount:
    image: "benjjefferies/nanonotifyaccount"
    environment:
    - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
    - DATABASE_URL=sqlite:////var/test.db
    ports:
    - "5000:5000"
    volumes:
    - ../:/var/
    restart: always
  nanotify:
    image: "benjjefferies/nanonotifier"
    environment:
    - EMAIL_ENABLED=True
    - DATABASE_URL=sqlite:////var/test.db
    - BCRYPT_SECRET=${BCRYPT_SECRET}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - TIMEOUT=5
    - RAIBLOCKS_HOST=[::1]
    volumes:
    - ../:/var/
    network_mode: host
    restart: always
  caddy:
    image: "abiosoft/caddy"
    ports:
    - "443:443"
    - "80:80"
    volumes:
    - ./caddy:/etc/
    - $HOME/.caddy:/root/.caddy
    restart: always
  nano:
    image: "nanocurrency/nano"
    volumes:
    - ./nano:/root
    restart: always
    ports:
    - "7076:7076"
