version: '3'
services:
  nanotifyaccount:
    image: "benjjefferies/nanonotifyaccount"
    ports:
     - "5000:5000"
    environment:
    - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
    - DATABASE_URL=sqlite:////var/test.db
    volumes:
    - ./:/var/
  nanotify:
    image: "benjjefferies/nanonotifier"
    environment:
    - EMAIL_ENABLED=True
    - DATABASE_URL=sqlite:////var/test.db
    - BCRYPT_SECRET=${BCRYPT_SECRET}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - TIMEOUT=5
    - RAIBLOCKS_HOST=[::1]
    volumes:
    - ./:/var/
    network_mode: host
